<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'title'            => 'The Great Gatsby',
                'author'           => 'F. Scott Fitzgerald',
                'isbn'             => '9780743273565',
                'category'         => 'Fiction',
                'total_copies'     => 15,
                'available_copies' => 15,
            ],
            [
                'title'            => 'To Kill a Mockingbird',
                'author'           => 'Harper Lee',
                'isbn'             => '9780061120084',
                'category'         => 'Classic',
                'total_copies'     => 32,
                'available_copies' => 32,
            ],
            [
                'title'            => '1984',
                'author'           => 'George Orwell',
                'isbn'             => '9780451524935',
                'category'         => 'Dystopian',
                'total_copies'     => 49,
                'available_copies' => 49,
            ],
            [
                'title'            => 'Clean Code',
                'author'           => 'Robert C. Martin',
                'isbn'             => '9780132350884',
                'category'         => 'Technology',
                'total_copies'     => 20,
                'available_copies' => 20,
            ],
            [
                'title'            => 'Pride and Prejudice',
                'author'           => 'Jane Austen',
                'isbn'             => '9780141439518',
                'category'         => 'Romance',
                'total_copies'     => 25,
                'available_copies' => 25,
            ],
            [
                'title'            => 'The Catcher in the Rye',
                'author'           => 'J.D. Salinger',
                'isbn'             => '9780316769488',
                'category'         => 'Fiction',
                'total_copies'     => 103,
                'available_copies' => 103,
            ],
            [
                'title'            => 'The Hobbit',
                'author'           => 'J.R.R. Tolkien',
                'isbn'             => '9780547928227',
                'category'         => 'Fantasy',
                'total_copies'     => 96,
                'available_copies' => 96,
            ],
            [
                'title'            => 'Fahrenheit 451',
                'author'           => 'Ray Bradbury',
                'isbn'             => '9781451673319',
                'category'         => 'Dystopian',
                'total_copies'     => 120,
                'available_copies' => 120,
            ],
            [
                'title'            => 'The Pragmatic Programmer',
                'author'           => 'Andrew Hunt, David Thomas',
                'isbn'             => '9780135957059',
                'category'         => 'Technology',
                'total_copies'     => 100,
                'available_copies' => 100,
            ],
            [
                'title'            => 'Brave New World',
                'author'           => 'Aldous Huxley',
                'isbn'             => '9780060850524',
                'category'         => 'Dystopian',
                'total_copies'     => 30,
                'available_copies' => 30,
            ],
            [
                'title'            => 'Design Patterns',
                'author'           => 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides',
                'isbn'             => '9780201633610',
                'category'         => 'Technology',
                'total_copies'     => 23,
                'available_copies' => 23,
            ],
            [
                'title'            => 'Moby-Dick',
                'author'           => 'Herman Melville',
                'isbn'             => '9781503280786',
                'category'         => 'Adventure',
                'total_copies'     => 45,
                'available_copies' => 45,
            ],
            [
                'title'            => 'War and Peace',
                'author'           => 'Leo Tolstoy',
                'isbn'             => '9781400079988',
                'category'         => 'Historical Fiction',
                'total_copies'     => 25,
                'available_copies' => 25,
            ],
            [
                'title'            => 'Crime and Punishment',
                'author'           => 'Fyodor Dostoevsky',
                'isbn'             => '9780486415871',
                'category'         => 'Classics',
                'total_copies'     => 30,
                'available_copies' => 30,
            ],
            [
                'title'            => 'The Alchemist',
                'author'           => 'Paulo Coelho',
                'isbn'             => '9780062315007',
                'category'         => 'Philosophy',
                'total_copies'     => 35,
                'available_copies' => 35,
            ],
            [
                'title'            => 'Introduction to Algorithms',
                'author'           => 'Thomas H. Cormen',
                'isbn'             => '9780262033848',
                'category'         => 'Computer Science',
                'total_copies'     => 24,
                'available_copies' => 24,
            ],
            [
                'title'            => 'Sapiens: A Brief History of Humankind',
                'author'           => 'Yuval Noah Harari',
                'isbn'             => '9780062316097',
                'category'         => 'Non-Fiction',
                'total_copies'     => 52,
                'available_copies' => 52,
            ],
            [
                'title'            => 'Atomic Habits',
                'author'           => 'James Clear',
                'isbn'             => '9780735211292',
                'category'         => 'Self-Help',
                'total_copies'     => 26,
                'available_copies' => 26,
            ],
            [
                'title'            => 'Dune',
                'author'           => 'Frank Herbert',
                'isbn'             => '9780441172719',
                'category'         => 'Science Fiction',
                'total_copies'     => 14,
                'available_copies' => 14,
            ],
            [
                'title'            => 'Refactoring: Improving the Design of Existing Code',
                'author'           => 'Martin Fowler',
                'isbn'             => '9780134757599',
                'category'         => 'Technology',
                'total_copies'     => 44,
                'available_copies' => 44,
            ],
            [
                'title'            => 'Things Fall Apart',
                'author'           => 'Chinua Achebe',
                'isbn'             => '9780385474542',
                'category'         => 'African Literature',
                'total_copies'     => 58,
                'available_copies' => 58,
            ],
            [
                'title'            => 'Kintu',
                'author'           => 'Jennifer Nansubuga Makumbi',
                'isbn'             => '9781786071477',
                'category'         => 'African Literature',
                'total_copies'     => 47,
                'available_copies' => 47,
            ],
            [
                'title'            => 'The First Woman',
                'author'           => 'Jennifer Nansubuga Makumbi',
                'isbn'             => '9781786078745',
                'category'         => 'African Literature',
                'total_copies'     => 35,
                'available_copies' => 35,    
            ],
            [
                'title'            => 'Abyssinian Chronicles',
                'author'           => 'Moses Isegawa',
                'isbn'             => '9780375405624',
                'category'         => 'African Literature',
                'total_copies'     => 34,
                'available_copies' => 34,
            ],
            [
                'title'            => 'The Lord of the Rings',
                'author'           => 'J.R.R. Tolkien',
                'isbn'             => '9780544003415',
                'category'         => 'Fantasy',
                'total_copies'     => 50,
                'available_copies' => 50,
            ],
            [
                'title'            => 'Harry Potter and the Sorcerer\'s Stone',
                'author'           => 'J.K. Rowling',
                'isbn'             => '9780590353427',
                'category'         => 'Fantasy',
                'total_copies'     => 67,
                'available_copies' => 67,
            ],
            [
                'title'            => 'Laravel Up & Running',
                'author'           => 'Matt Stauffer',
                'isbn'             => '9781492041214',
                'category'         => 'Technology',
                'total_copies'     => 42,
                'available_copies' => 42,
            ],
            [
                'title'            => 'You Don\'t Know JS Yet',
                'author'           => 'Kyle Simpson',
                'isbn'             => '9781985448377',
                'category'         => 'Technology',
                'total_copies'     => 38,
                'available_copies' => 38,
            ],
            [
                'title'            => 'Thinking, Fast and Slow',
                'author'           => 'Daniel Kahneman',
                'isbn'             => '9780374533557',
                'category'         => 'Psychology',
                'total_copies'     => 46,
                'available_copies' => 46,
            ],
            [
                'title'            => 'Deep Work',
                'author'           => 'Cal Newport',
                'isbn'             => '9781455586691',
                'category'         => 'Self-Help',
                'total_copies'     => 43,
                'available_copies' => 43,
            ],
            [
                'title'            => 'The Psychology of Money',
                'author'           => 'Morgan Housel',
                'isbn'             => '9780857197689',
                'category'         => 'Finance',
                'total_copies'     => 51,
                'available_copies' => 51,
            ],
            [
                'title'            => 'Rich Dad Poor Dad',
                'author'           => 'Robert T. Kiyosaki',
                'isbn'             => '9781612680194',
                'category'         => 'Finance',
                'total_copies'     => 50,
                'available_copies' => 50,
            ],
            [
                'title'            => 'Becoming',
                'author'           => 'Michelle Obama',
                'isbn'             => '9781524763138',
                'category'         => 'Memoir',
                'total_copies'     => 40,
                'available_copies' => 40,
            ],
            [
                'title'            => 'Educated',
                'author'           => 'Tara Westover',
                'isbn'             => '9780399590504',
                'category'         => 'Biography',
                'total_copies'     => 30,
                'available_copies' => 30,
            ],
        ];

        foreach ($books as $book) {
            Book::updateOrCreate(['isbn' => $book['isbn']], $book);
        }
    }
}
